version: '3.7'

services:
  neo4j:
    container_name: knowledge-graph-neo4j
    image: neo4j:community
    volumes:
       - "./db-conf/plugins:/plugins"
       - ./data:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms.security.procedures.allowlist=apoc.meta.data
      - NEO4J_dbms_security_procedures_unrestricted=apoc.meta.data
